Edit .onedev-buildspec.yml

diff --git a/.onedev-buildspec.yml b/.onedev-buildspec.yml
--- a/.onedev-buildspec.yml
+++ b/.onedev-buildspec.yml
@@ -23,6 +23,25 @@ jobs:
         cat vars.sh
     useTTY: true
     condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
+  - !CommandStep
+    name: Create/Destroy FreeIPA
+    runInContainer: false
+    interpreter: !DefaultInterpreter
+      commands: |
+        # Check if the argument is "create" or "destroy"
+        if [ "@param:ACTION@" == "create" ]; then
+            echo "Creating..."
+            /opt/freeipa-workshop-deployer/1_kcli/create.sh
+            /opt/freeipa-workshop-deployer/2_ansible_config/configure.sh
+        elif [ "@param:ACTION@" == "destroy" ]; then
+            echo "Destroying..."
+           /opt/freeipa-workshop-deployer/1_kcli/destroy.sh
+        else
+            echo "Invalid argument. Usage: $0 [create|destroy]"
+            exit 1
+        fi
+    useTTY: true
+    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
   paramSpecs:
   - !TextParam
     name: GIT_REPO
